FROM php:8.3-fpm-alpine

RUN apk add --no-cache supervisor \
    && mkdir -p /var/log/supervisor /var/run \
    && chown -R www-data:www-data /var/log/supervisor /var/run

WORKDIR /var/www

COPY ./supervisord.conf /etc/supervisord.conf
COPY ./supervisor.d /etc/supervisor.d/

ENTRYPOINT ["/usr/bin/supervisord", "-n", "-c", "/etc/supervisord.conf"]
